defmodule LevanngocWeb.FreeToolsLive.RobotsGenerator do
  use LevanngocWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    robots_list = [
      "Google",
      "Google Image",
      "Google Mobile",
      "MSN Search",
      "Yahoo",
      "Yahoo MM",
      "Yahoo Blogs",
      "Ask/Teoma",
      "Gigablast",
      "DMOZ Checker",
      "Nutch",
      "Alexa/Wayback",
      "Baidu",
      "Naver",
      "MSN PicSearch"
    ]

    {:ok,
     socket
     |> assign(:page_title, "Tạo File Robots.txt")
     |> assign(:robots_list, robots_list)
     |> assign(:default_robot, "Allowed")
     |> assign(:crawl_delay, "Default - No Delay")
     |> assign(:sitemap, "")
     |> assign(:restricted_directories, "")
     |> assign(:search_robots, Map.new(robots_list, fn r -> {r, "Same as Default"} end))
     |> assign(:generated_content, nil)
     |> LevanngocWeb.TrackToolVisit.track_visit("/robots-generator")}
  end

  @impl true
  def handle_event(
        "validate",
        %{"_target" => ["restricted_directories"], "restricted_directories" => val} = _params,
        socket
      ) do
    {:noreply, assign(socket, :restricted_directories, val)}
  end

  def handle_event("validate", %{"_target" => ["sitemap"], "sitemap" => val} = _params, socket) do
    {:noreply, assign(socket, :sitemap, val)}
  end

  def handle_event(
        "validate",
        %{"_target" => ["default_robot"], "default_robot" => val} = _params,
        socket
      ) do
    {:noreply, assign(socket, :default_robot, val)}
  end

  def handle_event(
        "validate",
        %{"_target" => ["crawl_delay"], "crawl_delay" => val} = _params,
        socket
      ) do
    {:noreply, assign(socket, :crawl_delay, val)}
  end

  def handle_event("validate", params, socket) do
    # Handle dynamic robot fields
    search_robots =
      Enum.reduce(socket.assigns.robots_list, socket.assigns.search_robots, fn robot, acc ->
        key = "robot_#{robot}"

        if Map.has_key?(params, key) do
          Map.put(acc, robot, params[key])
        else
          acc
        end
      end)

    # Also handle other fields if they came in bulk (though unlikely with standard phx-change on form)
    # But just in case
    sitemap = params["sitemap"] || socket.assigns.sitemap
    restricted = params["restricted_directories"] || socket.assigns.restricted_directories
    default = params["default_robot"] || socket.assigns.default_robot
    delay = params["crawl_delay"] || socket.assigns.crawl_delay

    {:noreply,
     socket
     |> assign(:search_robots, search_robots)
     |> assign(:sitemap, sitemap)
     |> assign(:restricted_directories, restricted)
     |> assign(:default_robot, default)
     |> assign(:crawl_delay, delay)}
  end

  @impl true
  def handle_event("generate", _params, socket) do
    content = build_robots_txt(socket.assigns)
    {:noreply, assign(socket, :generated_content, content)}
  end

  def handle_event("download", _params, socket) do
    content = build_robots_txt(socket.assigns)
    {:noreply, push_event(socket, "download_file", %{content: content, filename: "robots.txt"})}
  end

  def handle_event("clear", _params, socket) do
    {:noreply,
     socket
     |> assign(:default_robot, "Allowed")
     |> assign(:crawl_delay, "Default - No Delay")
     |> assign(:sitemap, "")
     |> assign(:restricted_directories, "")
     |> assign(
       :search_robots,
       Map.new(socket.assigns.robots_list, fn r -> {r, "Same as Default"} end)
     )
     |> assign(:generated_content, nil)}
  end

  defp build_robots_txt(assigns) do
    domain = System.get_env("PHX_HOST")
    lines = if domain, do: ["# robots.txt generated by #{domain}", ""], else: []

    # Default Robot
    lines =
      if assigns.default_robot == "Allowed" do
        lines ++ ["User-agent: *", "Disallow:"]
      else
        lines ++ ["User-agent: *", "Disallow: /"]
      end

    # Restricted Directories for Default
    lines =
      if assigns.restricted_directories != "" do
        dirs = String.split(assigns.restricted_directories, "\n", trim: true)

        Enum.reduce(dirs, lines, fn dir, acc ->
          acc ++ ["Disallow: " <> String.trim(dir)]
        end)
      else
        lines
      end

    # Crawl Delay
    lines =
      case assigns.crawl_delay do
        "Default - No Delay" ->
          lines

        val ->
          # Extract number from string logic or simple mapping
          # Assuming validation/values are simple
          seconds =
            case val do
              "5 Seconds" -> "5"
              "10 Seconds" -> "10"
              "20 Seconds" -> "20"
              "60 Seconds" -> "60"
              "120 Seconds" -> "120"
              _ -> nil
            end

          if seconds do
            lines ++ ["Crawl-delay: " <> seconds]
          else
            lines
          end
      end

    lines = lines ++ [""]

    # Specific Robots
    lines =
      Enum.reduce(assigns.robots_list, lines, fn robot, acc ->
        status = assigns.search_robots[robot]

        case status do
          "Same as Default" ->
            acc

          "Allowed" ->
            acc ++ ["User-agent: " <> get_user_agent(robot), "Disallow:", ""]

          "Refused" ->
            acc ++ ["User-agent: " <> get_user_agent(robot), "Disallow: /", ""]

          _ ->
            acc
        end
      end)

    # Sitemap
    lines =
      if assigns.sitemap != "" do
        lines ++ ["Sitemap: " <> assigns.sitemap]
      else
        lines
      end

    Enum.join(lines, "\n")
  end

  defp get_user_agent(robot) do
    case robot do
      "Google" -> "Googlebot"
      "Google Image" -> "Googlebot-Image"
      "Google Mobile" -> "Googlebot-Mobile"
      "MSN Search" -> "MSNBot"
      "Yahoo" -> "Slurp"
      "Yahoo MM" -> "Yahoo-MMCrawler"
      "Yahoo Blogs" -> "Yahoo-Blogs"
      "Ask/Teoma" -> "Teoma"
      "Gigablast" -> "Gigabot"
      "DMOZ Checker" -> "Robozilla"
      "Nutch" -> "Nutch"
      "Alexa/Wayback" -> "ia_archiver"
      "Baidu" -> "Baiduspider"
      "Naver" -> "NaverBot"
      "MSN PicSearch" -> "psbot"
      _ -> robot
    end
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div class="w-full h-full px-4 flex flex-col">
      <h1 class="text-3xl font-bold mb-6">Tạo File Robots.txt</h1>

      <form phx-change="validate" phx-submit="generate" class="flex flex-col gap-6">
        
    <!-- Default Robot -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
          <label class="font-bold">Mặc định - Tất cả Robots:</label>
          <div class="md:col-span-2">
            <select name="default_robot" class="select select-bordered w-full max-w-xs">
              <option value="Allowed" selected={@default_robot == "Allowed"}>
                Cho phép (Allowed)
              </option>
              <option value="Refused" selected={@default_robot == "Refused"}>
                Từ chối (Refused)
              </option>
            </select>
          </div>
        </div>
        
    <!-- Crawl Delay -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
          <label class="font-bold">Độ trễ thu thập (Crawl-Delay):</label>
          <div class="md:col-span-2">
            <select name="crawl_delay" class="select select-bordered w-full">
              <option value="Default - No Delay" selected={@crawl_delay == "Default - No Delay"}>
                Mặc định - Không có độ trễ
              </option>
              <option value="5 Seconds" selected={@crawl_delay == "5 Seconds"}>5 Giây</option>
              <option value="10 Seconds" selected={@crawl_delay == "10 Seconds"}>10 Giây</option>
              <option value="20 Seconds" selected={@crawl_delay == "20 Seconds"}>20 Giây</option>
              <option value="60 Seconds" selected={@crawl_delay == "60 Seconds"}>60 Giây</option>
              <option value="120 Seconds" selected={@crawl_delay == "120 Seconds"}>120 Giây</option>
            </select>
          </div>
        </div>
        
    <!-- Sitemap -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
          <label class="font-bold">
            Sitemap:
            <span class="font-normal text-sm text-base-content/70">(để trống nếu bạn không có)</span>
          </label>
          <div class="md:col-span-2">
            <input
              type="text"
              name="sitemap"
              value={@sitemap}
              placeholder="http://www.example.com/sitemap.xml"
              class="input input-bordered w-full"
            />
          </div>
        </div>
        
    <!-- Search Robots -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 items-start">
          <label class="font-bold pt-3">Search Robots (Các Robot tìm kiếm):</label>
          <div class="md:col-span-2 space-y-3">
            <%= for robot <- @robots_list do %>
              <div class="grid grid-cols-2 gap-4 items-center">
                <span class="text-sm">{robot}</span>
                <select name={"robot_" <> robot} class="select select-bordered select-sm w-full">
                  <option
                    value="Same as Default"
                    selected={@search_robots[robot] == "Same as Default"}
                  >
                    Giống mặc định
                  </option>
                  <option value="Allowed" selected={@search_robots[robot] == "Allowed"}>
                    Cho phép (Allowed)
                  </option>
                  <option value="Refused" selected={@search_robots[robot] == "Refused"}>
                    Từ chối (Refused)
                  </option>
                </select>
              </div>
            <% end %>
          </div>
        </div>
        
    <!-- Restricted Directories -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 items-start">
          <label class="font-bold pt-3">Thư mục hạn chế (Restricted Directories):</label>
          <div class="md:col-span-2">
            <p class="text-sm italic mb-2 text-base-content/70">
              Đường dẫn tính từ thư mục gốc và phải có dấu gạch chéo "/" ở cuối (ví dụ: /admin/) (mỗi thư mục trên một dòng)
            </p>
            <textarea
              name="restricted_directories"
              class="textarea textarea-bordered w-full h-40 font-mono"
              placeholder="/cgi-bin/"
            ><%= @restricted_directories %></textarea>
          </div>
        </div>
        
    <!-- Buttons -->
        <div class="flex flex-wrap gap-2 mt-4 justify-end">
          <button type="button" phx-click="generate" class="btn btn-primary text-white">
            Tạo robots.txt
          </button>
          <button type="button" phx-click="download" class="btn btn-error text-white">
            Tạo và Tải xuống robots.txt
          </button>
          <button type="button" phx-click="clear" class="btn btn-info text-white">
            Làm mới (Clear)
          </button>
        </div>
      </form>

      <%= if @generated_content do %>
        <div class="mt-8">
          <h3 class="font-bold text-lg mb-2">Nội dung robots.txt được tạo:</h3>
          <div class="mockup-code bg-black relative group">
            <button
              type="button"
              class="bg-transparent absolute top-2 right-2 text-primary-content opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-2 cursor-pointer px-2.5 py-1"
              onclick="copyToClipboard('generated-robots-txt', this)"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-5 w-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                />
              </svg>
              Sao chép
            </button>
            <pre class="px-4 before:!content-none" data-prefix="" id="generated-robots-txt"><code><%= @generated_content %></code></pre>
          </div>
        </div>
      <% end %>
    </div>
    <script>
      function copyToClipboard(elementId, btnElement) {
        const content = document.getElementById(elementId).innerText;
        navigator.clipboard.writeText(content).then(function() {
          const originalContent = btnElement.innerHTML;
          btnElement.innerHTML = `
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-success" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
            </svg>
            <span class="text-success">Đã sao chép</span>
          `;

          setTimeout(() => {
            btnElement.innerHTML = originalContent;
          }, 1500);
        });
      }

      window.addEventListener("phx:download_file", (e) => {
        const element = document.createElement('a');
        element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(e.detail.content));
        element.setAttribute('download', e.detail.filename);
        element.style.display = 'none';
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
      });
    </script>
    """
  end
end
