import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :levanngoc, LevanngocWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Override success_url for production (should be set via runtime config or environment variable)
# config :levanngoc, success_url: "https://yourdomain.com/user/billing"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger,
  level: :info

config :logger, :file_log,
  path: "development.log",
  level: :info,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]
